info:
  description: Amazon EC2 Auto Scaling helps you maintain application availability
    and allows you to dynamically scale your Amazon EC2 capacity up or down automatically
    according to conditions you define.
  termsOfService: https://docs.aws.amazon.com/autoscaling/plans/APIReference/Welcome.html
  title: Amazon_Auto_Scaling_API
  version: '1.0'
openapi: 3.0.0
security:
 -  Amazon_Auto_Scaling_Key: []
servers:
- description: Amazon AutoScale
  url: https://autoScaling.amazonaws.com
components:
  responses:
    '404':
      description: invalid parameters
  securitySchemes:
    Amazon_Auto_ScalingKey:
      description: Amazon AutoScale key
      in: header
      name: AuthKey
      type: apiKey
paths:
  /?Action=CreateScalingPlan:
    post:
      description: Create a scaling plan. A scaling plan contains a set of instructions
        used to configure dynamic scaling for the scalable resources in your application.
        AWS Auto Scaling creates target tracking scaling policies based on the scaling
        instructions in your scaling plan.
      parameters:
      - description: The name of the scaling plan.
        in: query
        name: scalingPlanName
        required: true
        schema:
          type: string
      responses:
        '404':
          $ref: '#/components/responses/404'
      servers:
      - url: https://autoScaling.amazonaws.com
      summary: Creates a scaling plan.
      tags:
      - create_scaling_plan